### ISSUE TITLE
Colors are not exported

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_font_color#8]
At least not in HTML...

**Comment by JohnMcLear** [comment]
cc @lpagliari

**Comment by lpagliari** [comment]
@rugk Can you confirm if your issue is fixed, please?

**Comment by rugk** [comment]
@JohnMcLear Can you publish a new version of this package?

In my installation it does not even have a `/static/css` dir.

**Comment by JohnMcLear** [comment]
done

**Comment by rugk** [comment]
Now colors do not work at all anymore. Even in the Etherpad they are not displayed.
Also choosing a color does not work.

**Comment by JohnMcLear** [comment]
@lpagliari I guess this is from your commits?

**Comment by rugk** [comment]
Wait, no...
Now it works....

I just fixed my "issue" that I had installed two headline addons (too stupid of me), so this could be the reason.

**Comment by rugk** [comment]
So I can confirm: It works, basically...

But: It does not work in any headline.., (only using [your addon](https://github.com/johnmclear/ep_headings2) now)

**Comment by JohnMcLear** [comment]
I think the heading stuff is due to no working async implementation of line styling attrs, I haven't had time to fix it yet and probably wont for a bit.

**Comment by rugk** [comment]
Okay, so  better track this in https://github.com/JohnMcLear/ep_headings2/issues/9 as in headers really all formatting is lost.
